### PR TITLE
Update UI

### LINKED ISSUE #224: Update UI
Update UI

### PR DESCRIPTION
**Pull request by yanlynnnnn**
Update UI

### CODE REVIEW

**Comment by yanlynnnnn** [comment]
Screenshot 2020-10-28 at 1 15 58 PM
Screenshot 2020-10-28 at 1 16 16 PM
Screenshot 2020-10-28 at 1 15 48 PM

**Review by hanstirtaputra — APPROVED** [review]
LGTM

**Review by RuiFengg — APPROVED** [review]
LGTM

**Comment by RuiFengg** [comment]
Could find a way to extract out the different color slots in the future

**Pull request merged**
